### ISSUE TITLE
运行报错：AttributeError: Can't get attribute '_LinearWithBias' on <module 'torch.nn.modules.linear

### ISSUE THREAD

**Issue by Web-AK** [kwwcv/iaanet#4]
AttributeError: Can't get attribute '_LinearWithBias' on <module 'torch.nn.modules.linear'
![image](https://github.com/kwwcv/iaanet/assets/60963694/6c203102-6bc8-47a8-92a7-375201b8efba)
想问问作者的具体CUDA、torchvision的配置

**Comment by ji-jessica** [comment]
您好 我遇到了相同的问题，想问您解决了吗

**Comment by kwwcv** [comment]
这是pytorch版本的问题，建议用更老的版本以直接跑通代码
[https://github.com/facebookresearch/TimeSformer/issues/63](https://github.com/facebookresearch/TimeSformer/issues/63)

**Comment by Web-AK** [comment]
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
@kwwcv 您好，我用的也是3090想问问您的CUDA版本  我的CUDA10.2创建了新的虚拟环境安装pytorch1.7.1还是报错不兼容，不支持NVIDIA 3090：
![image](https://github.com/kwwcv/iaanet/assets/60963694/33d550a3-5dfd-4ce3-b355-e979f6a7299d)
![image](https://github.com/kwwcv/iaanet/assets/60963694/cac02d9a-3915-485c-82ff-feb3f5239298)

**Comment by Web-AK** [comment]
porch1.8.1 CUDA10.2  torchvision 0.9.1还是不行
![image](https://github.com/kwwcv/iaanet/assets/60963694/9bf5f816-52f4-492e-aa37-b3ba1e752514)
![image](https://github.com/kwwcv/iaanet/assets/60963694/ef6fa17a-8d43-4dbe-95ac-e492f36122ef)

**Comment by ji-jessica** [comment]
您好 看到你closed 这个issue 想问一下您怎么解决的这个问题呢最后

**Comment by Web-AK** [comment]
@ji-jessica 解决了 换老的pytorch版本就行

**Comment by ji-jessica** [comment]
好的 我尝试修改了库函数目前可以运行代码 我换老版本的pytorch好像显示和cuda版本不兼容

**Comment by Web-AK** [comment]
是的 我当时重新安装的CUDA和相匹配的pytorch。最近在研究（PD-FA）ROC曲线如何绘制？你尝试过没有？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月27日(星期一) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [kwwcv/iaanet] 运行报错：AttributeError: Can&#39;t get attribute &#39;_LinearWithBias&#39; on <module &#39;torch.nn.modules.linear (Issue #4)





 
好的 我尝试修改了库函数目前可以运行代码 我换老版本的pytorch好像显示和cuda版本不兼容

**Comment by ji-jessica** [comment]
这个图我没有自己尝试过绘制 不过在ACM等模型的代码中metric文件中都有计算pd fa的值 你可以考虑参考一下

**Comment by Web-AK** [comment]
同学，你好。你也是做红外小目标检测方向的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月27日(星期一) 下午5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [kwwcv/iaanet] 运行报错：AttributeError: Can&#39;t get attribute &#39;_LinearWithBias&#39; on <module &#39;torch.nn.modules.linear (Issue #4)





 
这个图我没有自己尝试过绘制 不过在ACM等模型的代码中metric文件中都有计算pd fa的值 你可以考虑参考一下
